### ISSUE TITLE
Upvote replies

### ISSUE THREAD

**Issue by joedixon** [laravelio/portal#414] opened 2019-08-07 07:40 UTC
As a user, I want to be able to see the helpfulness of a given reply so that I have a better idea whether or not it will solve my issue.

**Comment by driesvints** [comment] 2019-08-07 11:07
Think this is a duplicate of https://github.com/laravelio/portal/issues/334 ? I wouldn't put to much "likes" and "upvote" features in it and just keep it simple with one of those.

**Closed** 2019-12-30 16:21 UTC
Labels: feature
