### ISSUE TITLE
Unable to run portal in local machine

### ISSUE THREAD

**Issue by iamakshaykh** [laravelio/portal#340] opened 2018-01-19 11:28 UTC
I have installed laravelio/portal in my local machine by following steps specified in repo readme but am not able to run portal getting error as specified below

`ErrorException (E_ERROR)
The Mix manifest does not exist. (View: /home/vagrant/Code/laravelio-test/resources/views/layouts/base.blade.php) (View: /home/vagrant/Code/laravelio-test/resources/views/layouts/base.blade.php)`

attaching screenshot
![capture](https://user-images.githubusercontent.com/12766618/35148869-fb9096e4-fd39-11e7-865b-f0fd6e6e73e1.JPG)

**Comment by wilburpowery** [comment] 2018-01-31 20:58
This get's fixed after running `npm install` and `npm run watch`.

Laravel Mix creates that file when you compile your assets.

**Comment by driesvints** [comment] 2018-01-31 22:41
I'm so sorry it took so long for me to answer. @iamakshaykh can you destroy the Vagrant box and do the exact same steps from the readme again? Then copy/paste all the output it gives so we can get a better look.

@wilburpowery normally the installation steps make sure that the Mix file gets created.

**Comment by wilburpowery** [comment] 2018-01-31 22:54
@driesvints, I tried forking the repo earlier today and got the same error. Also got a really strange MySql error. I’ll create an issue about it later.

**Comment by driesvints** [comment] 2018-01-31 22:55
I'll try to reproduce as soon as I find some time.

**Comment by driesvints** [comment] 2018-02-18 19:36
Gonna close this because I can't reproduce this. Let me know if you still experience this problem.

**Closed by driesvints** 2018-02-18 19:36 UTC
Labels: bug
